channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.7, <3.12
  - pip
  - setuptools <= 65.6.3
  - fenics
  - h5py
  - matplotlib
  - numpy
  - scipy
  - jupyter
  - notebook <= 6.3.0
  - nibabel
  - pydicom
  - snakemake >= 7.32.3
  - pint
  - meshio
  - svmtk <= 1.3.0
  - tqdm
